env:
  TERM: xterm-256color
font:
  normal:
    family: Victor Mono
    style: Light
  bold:
    family: Victor Mono
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Victor Mono
    style: Light Italic
    size: 11.5

colors:
  primary:
    background: '0x2B2D2E'
background_opacity: 0.9

key_bindings:
  - { key: K, mods: Command, chars: "\x02\x0B\x0C" }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
